spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    schemas: PUBLIC
server:
  port: 8081
rest:
  connect.timeout: 3000
  read.timeout: 5000
app:
  envName: test
logging:
  level:
    htnk128.kotlin.spring.boot.ddd.sample.contacts: DEBUG
    Exposed: DEBUG
